unique_ids:
  forms:
    home: CRUMT5RBOPXKFGYKMFWS2ZWODV4WMUGO
  modules: {}
  server_modules:
    main: '1657191836543603177485300.1339'
  assets:
    Prototyp Stephan.jpg: '1657191753089496115248950.7823'
    standard-page.html: 5KNXMOOMKNXFQHPZSDPFM2DNWL6SARX4
    theme.css: DATA6BGEDWR4WVO4N36WYJ4UGITAXPI5
